# Standard
cols = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'PATTERN',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1', 'FIL_SHAPE',
        'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
        'RIC_COMPOUND', 'RIC_STEP_GAUGE2', 'PCI_WIDTH', 'PRE_CURING_TEMPERATURE',
        'AIR', 'TEST_LOAD', 'RIM_WIDTH']

scale_cols = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
              'TUH_1',  'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'RIC_STEP_GAUGE2', 'PCI_WIDTH',
              'AIR', 'TEST_LOAD', 'RIM_WIDTH']

# cols = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'PATTERN',
#         'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
#         'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
#         'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
#         'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1', 'FIL_SHAPE',
#         'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
#         'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
#         'RIC_COMPOUND', 'RIC_STEP_GAUGE2', 'PCI_WIDTH', 'PRE_CURING_TEMPERATURE',
#         'JLC_MATERIAL_1', 'JLC_MATERIAL_2', 'C01_MATERIAL_1', 'C01_MATERIAL_2',
#         'JLC_EPI', 'BT1_EPI', 'C01_EPI',
#         'FS_AIR', 'FS_LOAD' #Flat Splotting 조건
#         'AIR', 'TEST_LOAD', 'RIM_WIDTH']
#
# scale_cols = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
#               'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
#               'TUH_1',  'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
#               'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'RIC_STEP_GAUGE2', 'PCI_WIDTH',
#               'JLC_MATERIAL_2','C01_MATERIAL_2', 'JLC_EPI', 'BT1_EPI', 'C01_EPI',
#               'FS_AIR', 'FS_LOAD', #Flat Splotting 조건
#               'AIR', 'TEST_LOAD', 'RIM_WIDTH']

# cols에서 TEST_LOAD 가 필요 없는 경우
cols1 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'PATTERN',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1',  'FIL_SHAPE',
        'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
        'RIC_COMPOUND', 'RIC_STEP_GAUGE2', 'PCI_WIDTH', 'PRE_CURING_TEMPERATURE',
        'AIR', 'RIM_WIDTH']
scale_cols1 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
              'TUH_1',  'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'RIC_STEP_GAUGE2', 'PCI_WIDTH',
              'AIR', 'RIM_WIDTH']

# cols에서 PATTERN이 필요 없는 경우
cols2 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1',  'FIL_SHAPE',
        'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
        'RIC_COMPOUND', 'RIC_STEP_GAUGE2', 'PCI_WIDTH', 'PRE_CURING_TEMPERATURE',
        'AIR', 'TEST_LOAD', 'RIM_WIDTH']

scale_cols2 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
              'TUH_1',  'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'RIC_STEP_GAUGE2', 'PCI_WIDTH',
              'AIR', 'TEST_LOAD', 'RIM_WIDTH']

# cols에서 TEST_LOAD , PATTERN 이 필요 없는 경우
# FT, 모달 에서 사용
cols3 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1',  'FIL_SHAPE',
        'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
        'RIC_COMPOUND', 'PCI_WIDTH', 'PRE_CURING_TEMPERATURE',
        'AIR', 'RIM_WIDTH']
scale_cols3 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
              'TUH_1',  'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'PCI_WIDTH',
              'AIR', 'RIM_WIDTH']

# cols에서 PATTERN이 필요 없는 경우
cols_DS = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'FIL_SHAPE',
        'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
        'AIR', 'TEST_LOAD', 'RIM_WIDTH']

scale_cols_DS = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'BT1_EPI', 'C01_EPI',
              'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH',
              'AIR', 'TEST_LOAD', 'RIM_WIDTH']


# cols에서 PATTERN이 필요 없는 경우
cols_SPF = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1',  'FIL_SHAPE',
        'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH','RIC_STEP_GAUGE2',
        'AIR', 'TEST_LOAD', 'RIM_WIDTH']

scale_cols_SPF = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
              'TUH_1',  'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'RIC_STEP_GAUGE2',
              'AIR', 'TEST_LOAD', 'RIM_WIDTH']

# Ford Data 시뮬레이션에 사용 - 이부영
cols_L = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'PATTERN', 'CTB_COMPOUND',
          'SUT_COMPOUND', 'PRE_COMPOUND2_GAUGE',	'JLC_MATERIAL',
          'PRE_BELT_TYPE', 'BT1_WIDTH', 'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE',
          'CTS_BELT_LIFT', 'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1',
           'CTS_C_C_LIFT',	'BSW_COMPOUND',	'BSW_STEP_GAUGE_TOP','BSW_STEP_GAUGE_BOT' ,	'BEAD_SINGLE_STRANDS2',
          'FIL_SHAPE', 'FIL_COMPOUND', 'FIL_WIDTH', 'RIC_COMPOUND', 'L11_WIDTH',
          'PRE_CURING_TEMPERATURE', 'AIR', 'TEST_LOAD', 'RIM_WIDTH']

scale_cols_L = ['SIZE_NSW',	'SIZE_SERISE', 'SIZE_INCH',
                'PRE_COMPOUND2_GAUGE', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',	'C01_EPI',
                'TUH_1',  'CTS_C_C_LIFT', 'BSW_STEP_GAUGE_TOP','BSW_STEP_GAUGE_BOT', 'FIL_WIDTH',
                'L11_WIDTH', 'AIR',	'TEST_LOAD',	'RIM_WIDTH']

# HMCSP 시뮬레이션에 사용 - 최재영
cols_HMCSP = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'PATTERN',
        'CTB_COMPOUND', 'CTB_CENTER_GAUGE', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI',
        'CTS_C_C_LIFT', 'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2',  'FIL_COMPOUND', 'FIL_WIDTH', 'FIL_SHAPE',
        'RIC_COMPOUND', 'L11_WIDTH', 'PCI_WIDTH', 'PRE_CURING_TEMPERATURE',
        'AIR', 'TEST_LOAD', 'RIM_WIDTH']


scale_cols_HMCSP = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_CENTER_GAUGE',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
              'CTS_C_C_LIFT', 'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'L11_WIDTH', 'PCI_WIDTH',
              'AIR', 'TEST_LOAD', 'RIM_WIDTH']


# SPL_HKstd 에 사용 - 서종훈
cols4 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'PATTERN',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'FIL_SHAPE',
        'FIL_COMPOUND', 'FIL_WIDTH',
        'PCI_WIDTH',
        'AIR', 'TEST_LOAD', 'RIM_WIDTH']

scale_cols4 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
                 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'C01_EPI',
                 'FIL_WIDTH', 'PCI_WIDTH',
                 'AIR', 'TEST_LOAD', 'RIM_WIDTH']

# HMC Flatspot 사용 - 우태진
cols5 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
         'PRE_COMPOUND2_GAUGE', 'PRE_BELT_TYPE', 'BT1_WIDTH', 'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
         'PLY_LOCK', 'C01_EPI', 'TUH_1', 'FIL_SHAPE', 'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP',
         'BSW_STEP_GAUGE_BOT', 'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH', 'RIC_COMPOUND', 'RIC_STEP_GAUGE2',
         'PCI_WIDTH', 'JLC_MATERIAL_1', 'JLC_MATERIAL_2', 'C01_MATERIAL_1', 'C01_MATERIAL_2', 'JLC_EPI',
         'FS_AIR', 'FS_LOAD', 'AIR', 'TEST_LOAD']

scale_cols5 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2', 'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_EPI',
               'BT1_ANGLE', 'CTS_BELT_LIFT', 'C01_EPI', 'TUH_1', 'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
               'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'RIC_STEP_GAUGE2', 'PCI_WIDTH', 'JLC_MATERIAL_2', 'C01_MATERIAL_2',
               'JLC_EPI', 'FS_LOAD', 'TEST_LOAD']


# GMSP 조건. 김일식 사용
cols6 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'PATTERN',
        'CTB_COMPOUND', 'CTB_STEP_GAUGE2', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1', 'FIL_SHAPE',
        'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
        'RIC_COMPOUND', 'RIC_STEP_GAUGE2', 'PCI_WIDTH', 'PRE_CURING_TEMPERATURE',
        'JLC_MATERIAL_1', 'JLC_MATERIAL_2', 'C01_MATERIAL_1', 'C01_MATERIAL_2',
        'JLC_EPI', 'BT1_EPI', 'C01_EPI',
        'AIR', 'TEST_LOAD', 'RIM_WIDTH']

scale_cols6 = ['SIZE_NSW', 'SIZE_SERISE', 'SIZE_INCH', 'CTB_STEP_GAUGE2',
              'PRE_COMPOUND2_GAUGE', 'BT1_WIDTH', 'BT1_ANGLE', 'CTS_BELT_LIFT', 'BT1_EPI', 'C01_EPI',
              'TUH_1',  'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP',
              'BSW_STEP_GAUGE_BOT', 'FIL_WIDTH', 'RIC_STEP_GAUGE2', 'PCI_WIDTH',
              'JLC_MATERIAL_2','C01_MATERIAL_2', 'JLC_EPI', 'BT1_EPI', 'C01_EPI',
              'AIR', 'TEST_LOAD', 'RIM_WIDTH']


# 차량 소음 측정 리포트 분석에 사용
cols_v = ['PATTERN',
        'CTB_COMPOUND', 'SUT_COMPOUND',
        'PRE_COMPOUND2_GAUGE', 'JLC_MATERIAL', 'PRE_BELT_TYPE', 'BT1_WIDTH',
        'BT1_MATERIAL', 'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'PLY_LOCK', 'C01_MATERIAL', 'C01_EPI', 'TUH_1', 'FIL_SHAPE',
        'TRW_STEP_GAUGE2', 'BSW_COMPOUND', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'BEAD_SINGLE_STRANDS2', 'FIL_COMPOUND', 'FIL_WIDTH',
        'RIC_COMPOUND', 'RIC_STEP_GAUGE2', 'PCI_WIDTH']

scale_cols_v = ['PRE_COMPOUND2_GAUGE', 'BT1_WIDTH',
        'BT1_EPI', 'BT1_ANGLE', 'CTS_BELT_LIFT',
        'C01_EPI', 'TUH_1',
        'TRW_STEP_GAUGE2', 'BSW_STEP_GAUGE_TOP', 'BSW_STEP_GAUGE_BOT',
        'FIL_WIDTH',
        'RIC_STEP_GAUGE2', 'PCI_WIDTH']